create table if not exists public.commune_evaluations (
  id uuid primary key default gen_random_uuid(),
  province text not null,
  district text not null,
  commune text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),

  registered_voters_national_2023 text default '',
  registered_voters_commune_2022 text default '',
  voter_turnout_national_2023 text default '',
  voter_turnout_commune_2022 text default '',
  violence_cases_national_2023 text default '',
  violence_cases_commune_2022 text default '',
  high_school_diploma text default '',
  associate_degree text default '',
  bachelor_degree text default '',
  master_degree text default '',
  removed_council_members text default '',
  total_council_members text default '',
  female_council_members text default '',
  youth_council_members text default '',
  total_clerks text default '',
  female_clerks text default '',
  youth_clerks text default '',
  total_village_leaders text default '',
  female_village_leaders text default '',
  youth_village_leaders text default '',
  human_rights_violations text default '',
  public_forum_participants text default '',
  council_meeting_participants text default '',
  planning_process_participants text default '',
  has_project_management_committee text default '',
  administrative_service_recipients text default '',
  community_projects_count text default '',
  service_request_cases text default '',
  service_resolved_cases text default '',
  religious_dispute_cases text default '',
  political_dispute_cases text default '',
  has_community_cultural_space text default '',
  commune_guard_count text default '',
  commune_guard_training_count text default '',
  commune_guard_support text default '',
  administrative_police_count text default '',
  police_training_count text default '',
  police_support text default '',
  crime_suppression_rate text default '',
  crime_education_programs text default '',
  crime_education_participants text default '',
  has_traffic_management text default '',
  traffic_signs_status text default '',
  traffic_accident_cases text default '',
  orderly_places text default '',
  disorderly_places text default '',
  has_public_parking text default '',
  traffic_law_education_sessions text default '',
  traffic_law_education_participants text default '',
  service_recipients_count text default '',
  birth_registrations text default '',
  marriage_registrations text default '',
  death_registrations text default '',
  residence_book_issued text default '',
  identity_cards_issued text default '',
  feedback_methods text default '',
  has_council_member_school_committee text default '',
  has_district_member_school_committee text default '',
  school_meeting_count text default '',
  has_teacher_support text default '',
  teacher_support_details text default '',
  scholarship_percentage text default '',
  primary_healthcare_recipients text default '',
  has_health_center text default '',
  has_referral_hospital text default '',
  has_doctor_incentives text default '',
  doctor_support_details text default '',
  has_community_health_participation text default '',
  has_public_exercise_space text default '',
  health_awareness_programs text default '',
  health_awareness_participants text default '',
  new_concrete_roads text default '',
  new_concrete_road_km text default '',
  new_asphalt_roads text default '',
  new_asphalt_road_km text default '',
  repaired_dirt_roads text default '',
  repaired_dirt_road_km text default '',
  repair_concrete_roads text default '',
  repair_concrete_road_km text default '',
  repair_asphalt_roads text default '',
  repair_asphalt_road_km text default '',
  construct_dirt_roads text default '',
  construct_dirt_road_km text default '',
  upgraded_road_lines text default '',
  upgraded_road_km text default '',
  drainage_lines text default '',
  drainage_meters text default '',
  pumping_stations text default '',
  water_treatment_plants text default '',
  private_community_projects text default '',
  private_community_projects_km text default '',
  clean_water_pct text default '',
  piped_water_pct text default '',
  small_reservoirs text default '',
  restored_water_bodies text default '',
  restored_water_bodies_m text default '',
  irrigation_canals text default '',
  irrigation_canals_meters text default '',
  water_inlet_systems text default '',
  water_management_training text default '',
  farming_communities text default '',
  farming_community_training text default '',
  has_drought_pumping text default '',
  electricity_coverage_pct text default '',
  has_commune_website text default '',
  has_health_center_website text default '',
  has_school_website text default '',
  has_police_website text default '',
  land_dispute_cases text default '',
  has_land_use_plan text default '',
  target_communities text default '',
  has_waste_collection text default '',
  environmental_law_programs text default '',
  environmental_law_participants text default '',
  green_village_programs text default '',
  has_green_village_program text default '',
  food_safety_programs text default '',
  food_poisoning_cases text default '',
  has_emergency_response text default '',
  has_disaster_preparedness text default '',
  has_human_rights_protection text default '',
  small_businesses_count text default '',
  registered_small_businesses text default '',
  has_financial_literacy text default '',
  has_youth_skills_training text default '',
  has_community_market text default '',
  has_cultural_promotion text default '',
  has_arts_training text default '',
  natural_resource_crime_cases text default '',
  has_new_market_projects text default '',
  new_market_details text default '',
  tourism_communities text default '',
  market_count text default '',
  has_market_management text default '',
  market_management_quality text default '',
  border_area_infrastructure_projects text default '',
  border_area_infrastructure_details text default '',
  has_disabled_child_care_services text default '',
  minority_needs_included text default '',
  minority_projects_implemented text default '',
  minority_candidates_2022 text default '',
  minority_council_members_2022to2026 text default '',
  has_support_infrastructure_for_disabled_elderly text default '',
  has_community_care_facility text default '',
  disabled_candidates_2022 text default '',
  disabled_council_members_2022to2026 text default '',
  poor_households_relief_count text default '',
  has_gender_mainstreaming_plan text default '',
  women_children_led_small_businesses text default '',
  gender_mainstreaming_plan_details text default '',
  problems_assessment_sessions text default '',
  citizens_participating_council_meetings text default '',
  citizen_participation_mechanisms text default '',
  dispute_resolution_rate text default '',
  legal_awareness_programs_count text default '',
  council_inspections_count text default '',
  disciplined_council_members text default '',
  disciplined_village_chiefs text default '',
  disciplined_commune_leaders text default '',
  has_received_incentives text default '',
  citizen_requests_escalated text default '',
  has_council_in_school_management text default '',
  community_preschools_count text default '',
  has_managed_protected_area text default '',
  climate_resilience_projects text default '',
  has_climate_change_awareness text default '',
  has_council_in_health_management text default '',
  has_child_protection_services text default '',
  has_waste_management text default '',
  waste_management_details text default '',
  has_managed_community_market text default '',
  disaster_affected_citizens text default '',
  has_clean_water_sanitation text default '',
  clean_water_projects text default '',
  toilet_construction_projects text default '',
  has_gender_equality_projects text default '',
  gender_equality_projects_count text default '',
  other_essential_functions text default '',
  has_mobilized_development_support text default '',
  mobilized_budget_amount text default '',
  village_leaders_with_bachelor text default '',
  village_leaders_with_associate text default '',
  village_leaders_with_high_school text default '',
  village_leaders_disciplined text default ''
);

alter table public.commune_evaluations enable row level security;

create policy "Allow all" on public.commune_evaluations
  for all
  to authenticated, anon
  using (true)
  with check (true);

-- Trigger to keep updated_at current
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

-- Drop and recreate trigger to avoid duplicates
drop trigger if exists commune_evaluations_updated_at on public.commune_evaluations;
create trigger commune_evaluations_updated_at
  before update on public.commune_evaluations
  for each row execute function public.set_updated_at();
